### ISSUE TITLE
A lot of complete code repos out there for you to sue.

### ISSUE THREAD

**Issue by andre-sonect** [codebucks27/The-Weirdos-NFT-Website-Starter-Code#12]
https://github.com/Marlinsk/landing-page-The-Weirdos-NFT-Website-React
https://github.com/carlosAndress101/The-Weirdos-NFT-Website?ref=reactjsexample.com

**Comment by codebucks27** [comment]
Hey, 

Thank you so much for letting me know. 
I have checked the first repo and I think it has given proper attribution to the original video. 
For the second repo I have opened an issue in that repository.
I think I should have some kind of license for these codes. Thanks anyway.
